#define SVWPT_PAGE_1 4

extern int far init_artist10();
extern void far close_board();
extern void far test_board();
extern void far my_set_viewport();
extern void far my_lock_viewport();
extern void far my_scroll();
extern void far my_color();
extern void far color_reg();
extern void far my_dash_pattern();
extern void far my_dash_enable();
extern void far my_line_xy();
extern void far place_char();
extern void far my_size_chars();
extern void far clear_screen();
extern void far clear_page();
extern void far draw_mode();
extern void far draw_line();
extern void far dot_plot();
extern void far draw_circle();
extern void far display_charactor();
extern void far my_circle();
extern void far redisplay_charactor();
extern void far move_redisplay();
