

rem      LINK ALL THE STANDARD D135 EMULATOR VERSIONS




rem       LINK THE 3 ARTIST VERSIONS


link @c:\emulate\d135a1024.res

link @c:\emulate\d135a800.res

link @c:\emulate\d135a640.res


rem       LINK THE METHEUS VERSION


link @c:\emulate\d135metheus.res



rem       LINK THE VECTRIX VERSION


link @c:\emulate\d135vectr.res



rem      LINK THE STANDARD (SLOW) CLIPPER VERSION


link @c:\emulate\d135sclipp.res



